<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2014.3.0.295
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Cruising Krakow - Contact Form Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'info@cruisingkrakow.com',
		'to' => 'info@cruisingkrakow.com'
	),
	'fields' => array(
		'custom_U17246' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Name',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Name\' is required.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'Email',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Email\' is required.',
				'format' => 'Field \'Email\' has an invalid email.'
			)
		),
		'custom_U17236' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Custom',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Custom\' is required.'
			)
		),
		'custom_U17258' => array(
			'order' => 4,
			'type' => 'checkbox',
			'label' => '      Segway tour',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U17254' => array(
			'order' => 5,
			'type' => 'checkbox',
			'label' => '      Bike Tour',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U17250' => array(
			'order' => 6,
			'type' => 'checkbox',
			'label' => '      Bike Rental',
			'required' => false,
			'errors' => array(
			)
		)
	)
);

process_form($form);
?>
